<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepResearchAgent.Core\DeepResearchAgent.Core.csproj" />
    <ProjectReference Include="..\DeepResearchAgent.Engine\DeepResearchAgent.Engine.csproj" />
  </ItemGroup>

</Project>
